In [ ]:
from statistics import correlation

import pandas as pd

import sys
sys.path.append("../")

import src.features
import importlib

importlib.reload(src.features)

gen = src.features.generate_features

In [95]:
train_start_date="1970-01-31"
test_end_date="1999-12-31"


av= gen(train_start_date,test_end_date)


#display(av)
display(av.xs('AEP', level='stock'))

feature,price_m,ret_m1,ret_m3,ret_m6,ret_next_month,ret_y1,vol_m1,vol_m3,vol_m6,vol_y1
date,,,,,,,,,,
1971-02-28,0.866839,-0.009765,0.184243,0.257001,-0.005849,0.138500,0.011440,0.017220,0.015871,0.021396
1971-03-31,0.861769,-0.005849,0.055378,0.232691,-0.023284,0.047638,0.020239,0.019681,0.016826,0.021800
1971-04-30,0.841704,-0.023284,-0.038478,0.221951,-0.030068,0.030571,0.016371,0.016017,0.018634,0.019834
1971-05-31,0.816395,-0.030068,-0.058192,0.115329,-0.008662,0.169978,0.011062,0.015891,0.016555,0.018733
1971-06-30,0.809324,-0.008662,-0.060857,-0.008849,0.026628,0.210650,0.010010,0.012481,0.016081,0.016848
...,...,...,...,...,...,...,...,...,...,...
1999-07-31,11.267358,-0.124766,-0.085032,-0.194081,0.008789,-0.142071,0.157112,0.315721,0.260947,0.288224
1999-08-31,11.366388,0.008789,-0.128547,-0.115791,-0.020245,-0.134349,0.219631,0.291088,0.270862,0.281026
1999-09-30,11.136272,-0.020245,-0.134948,-0.120624,-0.034480,-0.190629,0.277154,0.217966,0.278081,0.271741
1999-10-31,10.752295,-0.034480,-0.045713,-0.126858,-0.011424,-0.281069,0.228861,0.241882,0.278801,0.255984
1999-11-30,10.629459,-0.011424,-0.064834,-0.185046,-0.040732,-0.281735,0.368830,0.291615,0.291351,0.262754

In [20]:
train_start_date="1970-01-31"
test_end_date="1999-12-31"

df= pd.read_csv('../data/raw/prices.csv', index_col='Date', parse_dates=True)

df = df.loc[train_start_date:test_end_date]


df_bench = pd.read_csv('../data/raw/prices_bench.csv', index_col='Date', parse_dates=True)
df_bench = df_bench.loc[train_start_date:test_end_date]

daily_ret = df.pct_change()
daily_ret_bench = df_bench.pct_change()
daily_ret = daily_ret.loc['1970-02-03':]
daily_ret_bench = daily_ret_bench.loc['1970-02-03':]
rolling_window = 252
min_periods = 126

#display(daily_ret_bench)


#display(daily_ret.rolling(window=rolling_window, min_periods=min_periods).cov(daily_ret_bench.loc[:,'^GSPC']))


beta_1y_daily = (
        daily_ret
        .rolling(window=rolling_window, min_periods=min_periods)
        .cov(daily_ret_bench.loc[:,'^GSPC'])
        .div(
            daily_ret_bench.loc[:,'^GSPC'].rolling(window=rolling_window, min_periods=min_periods).var(),
            axis=0
        )
    )
display(beta_1y_daily)

,AAPL,ABT,ADBE,ADM,AEP,AMAT,AMD,AMGN,AMZN,APD,...,TMO,TROW,TXN,UNH,UPS,USB,WFC,WMT,XOM,^GSPC
Date,,,,,,,,,,,,,,,,,,,,,
1970-02-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-02-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-02-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-02-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1970-02-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1999-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import yfinance as yf
import pandas as pd

start_date = "1970-01-31"
end_date = "2020-12-31"



prices= pd.read_csv('../data/raw/prices.csv', index_col='Date', parse_dates=True)

risk_free_rate = pd.read_csv('../data/raw/risk_free_rate.csv', index_col='Date', parse_dates=True)