In [94]:
import pandas as pd

import sys
sys.path.append("../")

import src.features
import importlib

importlib.reload(src.features)

gen = src.features.generate_features

In [95]:
train_start_date="1970-01-31"
test_end_date="1999-12-31"


av= gen(train_start_date,test_end_date)


#display(av)
display(av.xs('AEP', level='stock'))

feature,price_m,ret_m1,ret_m3,ret_m6,ret_next_month,ret_y1,vol_m1,vol_m3,vol_m6,vol_y1
date,,,,,,,,,,
1971-02-28,0.866839,-0.009765,0.184243,0.257001,-0.005849,0.138500,0.011440,0.017220,0.015871,0.021396
1971-03-31,0.861769,-0.005849,0.055378,0.232691,-0.023284,0.047638,0.020239,0.019681,0.016826,0.021800
1971-04-30,0.841704,-0.023284,-0.038478,0.221951,-0.030068,0.030571,0.016371,0.016017,0.018634,0.019834
1971-05-31,0.816395,-0.030068,-0.058192,0.115329,-0.008662,0.169978,0.011062,0.015891,0.016555,0.018733
1971-06-30,0.809324,-0.008662,-0.060857,-0.008849,0.026628,0.210650,0.010010,0.012481,0.016081,0.016848
...,...,...,...,...,...,...,...,...,...,...
1999-07-31,11.267358,-0.124766,-0.085032,-0.194081,0.008789,-0.142071,0.157112,0.315721,0.260947,0.288224
1999-08-31,11.366388,0.008789,-0.128547,-0.115791,-0.020245,-0.134349,0.219631,0.291088,0.270862,0.281026
1999-09-30,11.136272,-0.020245,-0.134948,-0.120624,-0.034480,-0.190629,0.277154,0.217966,0.278081,0.271741
1999-10-31,10.752295,-0.034480,-0.045713,-0.126858,-0.011424,-0.281069,0.228861,0.241882,0.278801,0.255984
1999-11-30,10.629459,-0.011424,-0.064834,-0.185046,-0.040732,-0.281735,0.368830,0.291615,0.291351,0.262754

In [4]:
Z=gen(df)
display(Z.dropna().head())
display(Z.loc['2011-01-31':])

                AAPL                                                    \
             price_m    ret_m1    ret_m3    ret_m6    ret_y1    vol_m1
Date
2010-08-31  7.530398 -0.014226 -0.000550  0.264228  0.511441  0.239280
2010-09-30  8.205398  0.089637  0.048653  0.225773  0.540335  0.404939
2010-10-31  9.016896  0.098898  0.180366  0.198232  0.560609  0.320222
2010-11-30  9.336116  0.035402  0.239791  0.239109  0.555452  0.167445
2010-12-31  9.632684  0.031766  0.173945  0.231061  0.615876  0.078946

                                              AMZN  ...         V        XOM  \
              vol_m3    vol_m6    vol_y1   price_m  ...    vol_y1    price_m
Date                                                ...
2010-08-31  0.222802  0.248798  0.216191  6.318636  ...  0.536213  33.492182
2010-09-30  0.266742  0.277348  0.231024  7.383214  ...  0.551305  34.017240
2010-10-31  0.321480  0.271956  0.241009  8.037071  ...  0.545973  36.131236
2010-11-30  0.297535  0.260169  0.240503  8.426071  ...  0.558930  38.884709
2010-12-31  0.188871  0.227806  0.229513  8.941955  ...  0.593550  40.414031

                                                                        \
              ret_m1    ret_m3    ret_m6    ret_y1    vol_m1    vol_m3
Date
2010-08-31  0.029968 -0.035372 -0.064196 -0.106153  0.703252  0.780941
2010-09-30  0.015677  0.016013 -0.067588 -0.094895  0.221114  0.527823
2010-10-31  0.062145  0.111125 -0.035973 -0.064781  0.727517  0.550628
2010-11-30  0.076208  0.161009  0.119941 -0.029664  0.719353  0.555995
2010-12-31  0.039330  0.188046  0.207070  0.048383  0.404916  0.617262


              vol_m6    vol_y1
Date
2010-08-31  0.712130  0.835456
2010-09-30  0.690467  0.818892
2010-10-31  0.761093  0.762384
2010-11-30  0.668468  0.744592
2010-12-31  0.572543  0.650173

[5 rows x 162 columns]

                  AAPL                                                     \
               price_m    ret_m1    ret_m3    ret_m6    ret_y1     vol_m1
Date
2011-01-31   10.138883  0.052550  0.124432  0.327241  0.629057   0.173342
2011-02-28   10.522488  0.037835  0.127073  0.397335  0.766550   0.214541
2011-03-31   10.411871 -0.010512  0.080890  0.268905  0.555389   0.248975
2011-04-30   10.199872 -0.020361  0.006015  0.131195  0.355435   0.232535
2011-05-31   10.240899  0.004022 -0.026761  0.096912  0.359193   0.182592
...                ...       ...       ...       ...       ...        ...
2025-08-31  224.151283  0.064144  0.102885 -0.055856  0.018343  10.271487
2025-09-30  242.024886  0.079739  0.209833  0.091498  0.088742   9.825357
2025-10-31  257.803836  0.065196  0.223908  0.287019  0.127974   7.937785
2025-11-30  271.333742  0.052481  0.210494  0.335036  0.197880   3.810420
2025-12-31  276.259593  0.018154  0.141451  0.380965  0.114092   4.316078

                                                AMZN  ...         V  \
              vol_m3    vol_m6    vol_y1     price_m  ...    vol_y1
Date                                                  ...
2011-01-31  0.139911  0.230696  0.228936    9.117625  ...  0.571574
2011-02-28  0.155610  0.226573  0.237685    9.055895  ...  0.573492
2011-03-31  0.212286  0.200579  0.238963    8.440196  ...  0.562246
2011-04-30  0.232017  0.185964  0.228960    9.228825  ...  0.556309
2011-05-31  0.221367  0.188489  0.224329    9.908333  ...  0.454553
...              ...       ...       ...         ...  ...       ...
2025-08-31  4.973227  7.093450  6.237533  224.670952  ...  7.120664
2025-09-30  7.411444  7.211420  6.702332  228.089523  ...  6.954954
2025-10-31  9.344876  6.472744  7.049043  222.150435  ...  6.827784
2025-11-30  7.191187  6.082207  6.995677  236.274211  ...  6.698743
2025-12-31  5.354761  6.383103  6.906461  229.187143  ...  7.332592

                   XOM                                                    \
               price_m    ret_m1    ret_m3    ret_m6    ret_y1    vol_m1
Date
2011-01-31   43.232265  0.069734  0.196534  0.329500  0.166994  1.087084
2011-02-28   47.214167  0.092105  0.214209  0.409707  0.319210  0.735536
2011-03-31   46.725576 -0.010348  0.156172  0.373585  0.280747  0.922204
2011-04-30   47.946777  0.026136  0.109051  0.327017  0.279281  0.873744
2011-05-31   46.485113 -0.030485 -0.015441  0.195460  0.338844  0.885216
...                ...       ...       ...       ...       ...       ...
2025-08-31  106.629972 -0.021047  0.041392  0.008033 -0.037942  2.960400
2025-09-30  111.368060  0.044435  0.052696  0.021807  0.027431  1.911228
2025-10-31  111.734053  0.003286  0.025812  0.080844 -0.027458  1.686733
2025-11-30  115.427539  0.033056  0.082506  0.127313  0.009866  2.078662
2025-12-31  117.129763  0.014747  0.051736  0.107158  0.110495  1.668446


              vol_m3    vol_m6    vol_y1
Date
2011-01-31  0.737118  0.643873  0.649624
2011-02-28  0.742512  0.649253  0.680691
2011-03-31  0.914941  0.766102  0.728284
2011-04-30  0.843828  0.790473  0.775783
2011-05-31  0.893722  0.818117  0.743292
...              ...       ...       ...
2025-08-31  2.974368  3.330870  2.754779
2025-09-30  2.313874  2.965530  2.738029
2025-10-31  2.186120  2.447940  2.691451
2025-11-30  1.892208  2.433288  2.723145
2025-12-31  1.811280  2.062577  2.538286

[180 rows x 162 columns]

KeyError: "None of ['date', 'stock'] are in the columns"