In [1]:
import pandas as pd
import numpy as np
import importlib
import time

from xgboost import XGBRegressor as XGB
from sklearn.ensemble import RandomForestRegressor as RF

from sklearn.linear_model import LinearRegression as LR

from sklearn.metrics import mean_squared_error

from sklearn.pipeline import Pipeline

import sys
sys.path.append("../")

import src.features

importlib.reload(src.features)
from src.features import generate_features as gen
from src.features import get_dataset, get_periods



from src.evaluate_prediction import prediction_df, evaluate_prediction, evaluate_Models
importlib.reload(src.evaluate_prediction)

In [2]:
Periods= get_periods("1970-01-31","2020-12-31")

# XGB model test

In [3]:

XGBModels={}
for j1 in range(1, 4):
    for j2 in range(1, 3):
        for j3 in range(0, 2):
            model=XGB(
                    n_estimators=100*j1,
                    learning_rate=0.01*(1+2*j2),
                    max_depth=j3,
                    subsample=0.6,
                    colsample_bytree=0.8,
                    reg_lambda=10,
                    reg_alpha=1,
                    random_state=42,
                    )

            name= 'XGB' + str(j1) + '_' + str(j2) + '_' + str(j3)
            XGBModels[name]= model

            print(name+': n_estimators =' + str(100*j1) + ' learning_rate=' + str(0.01*j2) + ', max_depth =' + str(j3))

XGB1_1_0: n_estimators =100 learning_rate=0.01, max_depth =0
XGB1_1_1: n_estimators =100 learning_rate=0.01, max_depth =1
XGB1_2_0: n_estimators =100 learning_rate=0.02, max_depth =0
XGB1_2_1: n_estimators =100 learning_rate=0.02, max_depth =1
XGB2_1_0: n_estimators =200 learning_rate=0.01, max_depth =0
XGB2_1_1: n_estimators =200 learning_rate=0.01, max_depth =1
XGB2_2_0: n_estimators =200 learning_rate=0.02, max_depth =0
XGB2_2_1: n_estimators =200 learning_rate=0.02, max_depth =1
XGB3_1_0: n_estimators =300 learning_rate=0.01, max_depth =0
XGB3_1_1: n_estimators =300 learning_rate=0.01, max_depth =1
XGB3_2_0: n_estimators =300 learning_rate=0.02, max_depth =0
XGB3_2_1: n_estimators =300 learning_rate=0.02, max_depth =1

In [ ]:
for i in Periods.index:
    Dataset= get_dataset(Periods.iloc[i])
    Z_train=Dataset["Z_train"]
    y_train=Dataset["y_train"]
    Z_valid=Dataset["Z_valid"]
    y_valid=Dataset["y_valid"]
    for names, model in XGBModels.items():
        model.fit(Z_train,y_train)
    info= pd.DataFrame({
        'start': [y_valid.index[0]],
        'end':[y_valid.index[-1]]
    })
    display(info)
    display(y_valid.columns)
    eval= evaluate_Models(Z_train,y_train,Z_valid,y_valid,XGBModels)
    eval= eval.sort_values("R2_valid", ascending=False)
    display(eval)

       start        end
0 1990-01-31 1994-12-31

Index(['AEP', 'BA', 'CAT', 'CVX', 'DIS', 'ED', 'IBM', 'IP', 'JNJ', 'KO', 'MCD',
       'MMM', 'MO', 'MRK', 'PG', 'XOM'],
      dtype='str')

          name  mqe_train  R2_train  mqe_valid  R2_valid
2     XGB1_1_1   0.058939  0.100285   0.049832  0.033241
1     XGB1_1_0   0.049904  0.354996   0.049839  0.032954
4     XGB1_2_1   0.058213  0.122299   0.049896  0.030766
6     XGB2_1_1   0.057864  0.132804   0.049916  0.029976
5     XGB2_1_0   0.045816  0.456326   0.049928  0.029528
3     XGB1_2_0   0.047000  0.427876   0.049933  0.029316
10    XGB3_1_1   0.057104  0.155445   0.049965  0.028087
9     XGB3_1_0   0.043707  0.505238   0.049973  0.027782
7     XGB2_2_0   0.043320  0.513961   0.050005  0.026520
8     XGB2_2_1   0.056927  0.160677   0.050018  0.025996
11    XGB3_2_0   0.041688  0.549890   0.050039  0.025178
12    XGB3_2_1   0.056035  0.186750   0.050089  0.023239
0   zero_guess   0.062137  0.000000   0.050682  0.000000

       start        end
0 1995-01-31 1999-12-31

Index(['AEP', 'BA', 'BAC', 'BMY', 'CAT', 'CL', 'CVX', 'DE', 'DIS', 'ED', 'EMR',
       'IBM', 'IP', 'ITW', 'JNJ', 'KO', 'LLY', 'MCD', 'MMM', 'MO', 'MRK',
       'PEP', 'PFE', 'PG', 'WFC', 'WMT', 'XOM'],
      dtype='str')

          name  mqe_train  R2_train  mqe_valid  R2_valid
6     XGB2_1_1   0.053884  0.147407   0.058746  0.093858
2     XGB1_1_1   0.054839  0.116897   0.058755  0.093568
4     XGB1_2_1   0.054153  0.138858   0.058756  0.093555
10    XGB3_1_1   0.053210  0.168596   0.058804  0.092066
8     XGB2_2_1   0.052996  0.175267   0.058805  0.092031
12    XGB3_2_1   0.052208  0.199598   0.058894  0.089292
1     XGB1_1_0   0.045958  0.379768   0.059073  0.083729
5     XGB2_1_0   0.042511  0.469312   0.059097  0.082995
3     XGB1_2_0   0.043337  0.448488   0.059115  0.082421
9     XGB3_1_0   0.040838  0.510270   0.059133  0.081875
7     XGB2_2_0   0.040310  0.522842   0.059146  0.081470
11    XGB3_2_0   0.038826  0.557343   0.059172  0.080645
0   zero_guess   0.058356  0.000000   0.061713  0.000000

       start        end
0 2000-01-31 2004-12-31

Index(['AEP', 'BA', 'BAC', 'BMY', 'CAT', 'CL', 'CVX', 'DE', 'DIS', 'ED', 'EMR',
       'IBM', 'IP', 'ITW', 'JNJ', 'KO', 'LLY', 'MCD', 'MMM', 'MO', 'MRK',
       'PEP', 'PFE', 'PG', 'WFC', 'WMT', 'XOM'],
      dtype='str')

          name  mqe_train  R2_train  mqe_valid  R2_valid
0   zero_guess   0.058875  0.000000   0.062411  0.000000
2     XGB1_1_1   0.055124  0.123385   0.063270 -0.027707
6     XGB2_1_1   0.054280  0.150007   0.063283 -0.028146
4     XGB1_2_1   0.054543  0.141768   0.063295 -0.028541
10    XGB3_1_1   0.053676  0.168840   0.063357 -0.030551
8     XGB2_2_1   0.053511  0.173937   0.063379 -0.031261
12    XGB3_2_1   0.052789  0.196080   0.063497 -0.035116
1     XGB1_1_0   0.046958  0.363874   0.063506 -0.035389
5     XGB2_1_0   0.043730  0.448312   0.063615 -0.038959
9     XGB3_1_0   0.041946  0.492419   0.063636 -0.039649
3     XGB1_2_0   0.044480  0.429217   0.063695 -0.041585
11    XGB3_2_0   0.039977  0.538946   0.063739 -0.043018
7     XGB2_2_0   0.041555  0.501821   0.063754 -0.043488

In [ ]:
# The circus of models

#LRmodel=LR()
RFmodel=RF(n_estimators=100)


XGBmodel1=XGB(
    n_estimators=100,
    learning_rate=0.03,
    max_depth=2,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_lambda=10,
    reg_alpha=1,
    random_state=42
)

XGBmodel2=XGB(
    n_estimators=300,
    learning_rate=0.01,
    max_depth=2,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_lambda=10,
    reg_alpha=1,
    random_state=42
)

Model= {
    #'LR model': LRmodel,
    'RF model': RFmodel,
    'XGBmodel1': XGBmodel1,
    'XGBmodel2': XGBmodel2

}

In [ ]:
Simulation_start_date=pd.Timestamp("1965-01-31")
Simulation_end_date=pd.Timestamp("2020-12-31")


train_years = 20
valid_years = 5
test_years = 5
step_years = 5

splits = []

train_start = Simulation_start_date
Periods_rows=[]
while True:
    train_end = train_start + pd.DateOffset(years=train_years) - pd.offsets.MonthEnd(1)
    valid_start = train_end + pd.offsets.MonthEnd(1)
    valid_end = valid_start + pd.DateOffset(years=valid_years) - pd.offsets.MonthEnd(1)
    test_start = valid_end + pd.offsets.MonthEnd(1)
    test_end = test_start + pd.DateOffset(years=test_years) - pd.offsets.MonthEnd(1)
    Periods_rows.append({
        'train_start': train_start,
        'train_end': train_end,
        'valid_start': valid_start,
        'valid_end': valid_end,
        'test_start': test_start,
        'test_end': test_end,
    })
    #print(train_start, train_end, valid_start, valid_end, test_start, test_end)
    if test_end > Simulation_end_date:
        break
    train_start+= pd.DateOffset(years=step_years)

Periods= pd.DataFrame(Periods_rows)
display(Periods)

In [ ]:






for names, model in Model.items():


    start_time = time.time()
    model.fit(Z_train,y_train)
    end_time = time.time()
    length_time = end_time - start_time
    print(names, ' fitted in ',round(length_time,2), ' seconds')

model_eval =evaluate_Models(Z_train,y_train,Z_valid,y_valid,Model)
model_eval=model_eval.sort_values("R2_valid", ascending=False)
print(model_eval)

In [ ]:
data_start=pd.Timestamp("1960-01-31")
train_start = pd.Timestamp("1965-01-31")
train_end = pd.Timestamp("1989-12-31")
valid_start = pd.Timestamp("1990-01-31")
valid_end_date = pd.Timestamp("2020-12-31")


def Run_model():
    yield

train_years = 20
valid_years = 5
test_years = 5
step_years = 5

splits = []

train_start = data_start

while True:
    train_end = train_start + pd.DateOffset(years=train_years) - pd.offsets.MonthEnd(1)
    valid_start = train_end + pd.offsets.MonthEnd(1)
    valid_end = valid_start + pd.DateOffset(years=valid_years) - pd.offsets.MonthEnd(1)
    test_start = valid_end + pd.offsets.MonthEnd(1)
    test_end = test_start + pd.DateOffset(years=test_years) - pd.offsets.MonthEnd(1)
    print(train_start, train_end, valid_start, valid_end, test_start, test_end)
    if test_end > valid_end_date:
        break
    train_start+= pd.DateOffset(years=step_years)

In [ ]:

Model= {
    'XGBmodel1': XGBmodel1,

}
model_eval =evaluate_Models(Z_train,y_train,Z_valid,y_valid,Model)
model_eval=model_eval.sort_values("R2_valid", ascending=False)
print(model_eval)

In [ ]:
'''Model2={}
for j1 in range(1, 5):
    for j2 in range(1, 4):
        for j3 in range(2, 4):
            model=XGB(
                    n_estimators=100*j1,
                    learning_rate=0.01*j2,
                    max_depth=j3,
                    subsample=0.6,
                    colsample_bytree=0.8,
                    reg_lambda=10,
                    reg_alpha=1,
                    random_state=42,
                    )

            model.fit(Z_train,y_train)
            name= 'XGB' + str(j1) + '_' + str(j2) + '_' + str(j3)
            Model2[name]= model

            print(name)

'''

In [ ]:
'''model2_eval =evaluate_Models(Z_train,y_train,Z_valid,y_valid,Model2)
model2_eval=model2_eval.sort_values("R2_valid", ascending=False)

display(model2_eval)'''