In [2]:
import sys

import pandas as pd

sys.path.append("../")
import src.features
from pathlib import Path

from src.features import generate_features as gen
from src.features import get_dataset, get_periods

from src.evaluate_prediction import  evaluate_prediction
import importlib
from itertools import product

import run_model
importlib.reload(run_model)

run= run_model.run_model

from xgboost import XGBRegressor as XGB
from sklearn.ensemble import RandomForestRegressor as RF

from sklearn.tree import DecisionTreeRegressor as DTR

from sklearn.neural_network import MLPRegressor

from sklearn.linear_model import LinearRegression as LR

from sklearn.metrics import mean_squared_error

from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge


from sklearn.linear_model import MultiTaskElasticNet
from sklearn.ensemble import ExtraTreesRegressor


from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

## Compare of XGB parameters

In [5]:
XGBModels={}
for j1 in range(1, 3):
    for j2 in range(1, 2):
        for j3 in range(1, 3):
            model=XGB(
                    n_estimators=500*j1,
                    learning_rate=0.01*j2,
                    max_depth=j3,
                    subsample=0.6,
                    colsample_bytree=0.8,
                    reg_lambda=10,
                    reg_alpha=1,
                    random_state=42,
                    )

            name= 'XGB' + str(j1) + '_' + str(j2) + '_' + str(j3)
            XGBModels[name]= model


            print(name+': n_estimators =' + str(500*j1) + ' learning_rate=' + str(0.01*j2) + ', max_depth =' + str(j3))

XGB1_1_1: n_estimators =500 learning_rate=0.01, max_depth =1
XGB1_1_2: n_estimators =500 learning_rate=0.01, max_depth =2
XGB2_1_1: n_estimators =1000 learning_rate=0.01, max_depth =1
XGB2_1_2: n_estimators =1000 learning_rate=0.01, max_depth =2

In [6]:
eval_summary_XGB, eval_mean_XGB=run(XGBModels,"1970-01-31","1999-12-31",train_years = 20, valid_years = 1,step_years = 1 ,max_steps = 10,print_years=True)

1990
1991
1992
1993
1994
1995
1996
1997
1998
1999

In [50]:
display(eval_summary_XGB)
#display(eval_mean_XGB.loc['average'])
display(eval_mean_XGB.sort_values(by=['average'], ascending=False, axis=1))


eval_stat =eval_summary_XGB.agg(['mean','std','min'])



display(eval_stat)

model,XGB1_1_0,XGB1_1_1,XGB1_1_2,XGB1_2_0,XGB1_2_1,XGB1_2_2,XGB2_1_0,XGB2_1_1,XGB2_1_2,XGB2_2_0,XGB2_2_1,XGB2_2_2
year,,,,,,,,,,,,
1990,0.1550,0.1130,0.1456,0.1632,0.1307,0.1709,0.1703,0.1313,0.1695,0.1619,0.1515,0.1855
1991,0.1264,0.1215,0.1191,0.1173,0.1185,0.1117,0.1278,0.1199,0.1135,0.1150,0.1138,0.1068
1992,-0.0013,0.0259,0.0374,-0.0308,0.0334,0.0381,-0.0236,0.0356,0.0462,-0.0690,0.0458,0.0396
1993,0.0711,0.0867,0.0848,0.0394,0.0827,0.0741,0.0431,0.0844,0.0735,0.0075,0.0734,0.0583

model,XGB2_1_2,XGB1_2_2,XGB2_2_2,XGB1_1_2,XGB2_2_1,XGB2_1_1,XGB1_2_1,XGB1_1_0,XGB1_1_1,XGB2_1_0,XGB1_2_0,XGB2_2_0
average,0.100675,0.0987,0.09755,0.096725,0.096125,0.0928,0.091325,0.0878,0.086775,0.0794,0.072275,0.05385

model,XGB1_1_0,XGB1_1_1,XGB1_1_2,XGB1_2_0,XGB1_2_1,XGB1_2_2,XGB2_1_0,XGB2_1_1,XGB2_1_2,XGB2_2_0,XGB2_2_1,XGB2_2_2
mean,0.087800,0.086775,0.096725,0.072275,0.091325,0.098700,0.079400,0.092800,0.100675,0.053850,0.096125,0.097550
std,0.068856,0.043202,0.046730,0.085635,0.043660,0.056743,0.086664,0.043047,0.053564,0.104331,0.046288,0.065114
min,-0.001300,0.025900,0.037400,-0.030800,0.033400,0.038100,-0.023600,0.035600,0.046200,-0.069000,0.045800,0.039600

## Comparisson of random forest models

In [75]:
RFModels={}


for n_estimators, max_depth, min_samples_leaf in product(
    [50, 100, 300,500],
    [None, 10],
    [1, 5]
):
    model= RF(
        n_estimators=n_estimators,
        max_depth=max_depth,
        min_samples_split=10,
        min_samples_leaf=min_samples_leaf,
        random_state=42,
        n_jobs=-1
    )
    name= 'RF' + str(n_estimators) + '_' + str(max_depth) + '_' + str(min_samples_leaf)
    RFModels[name]= model

In [76]:
eval_summary_RF, eval_mean_RF=run(RFModels,"1970-01-31","1999-12-31",train_years = 20, valid_years = 1,step_years = 1 ,max_steps = 3,print_years=True )

1990
1991
1992

In [77]:
display(eval_summary_RF)
display(eval_mean_RF)

model,RF100_10_1,RF100_10_5,RF100_None_1,RF100_None_5,RF300_10_1,RF300_10_5,RF300_None_1,RF300_None_5,RF500_10_1,RF500_10_5,RF500_None_1,RF500_None_5,RF50_10_1,RF50_10_5,RF50_None_1,RF50_None_5
year,,,,,,,,,,,,,,,,
1990,0.1914,0.1956,0.2005,0.1968,0.1923,0.2030,0.2106,0.2013,0.1924,0.2026,0.2085,0.2022,0.1828,0.1927,0.2083,0.2002
1991,0.1187,0.1194,0.1014,0.1105,0.1231,0.1105,0.1160,0.1080,0.1255,0.1089,0.1166,0.1014,0.1228,0.1284,0.1031,0.1346
1992,-0.0187,-0.0236,-0.1035,-0.0663,-0.0107,-0.0148,-0.0745,-0.0564,-0.0127,-0.0215,-0.0733,-0.0651,-0.0135,-0.0420,-0.1077,-0.0914

model,RF100_10_1,RF100_10_5,RF100_None_1,RF100_None_5,RF300_10_1,RF300_10_5,RF300_None_1,RF300_None_5,RF500_10_1,RF500_10_5,RF500_None_1,RF500_None_5,RF50_10_1,RF50_10_5,RF50_None_1,RF50_None_5
mean,0.097133,0.097133,0.066133,0.080333,0.101567,0.099567,0.084033,0.084300,0.101733,0.096667,0.083933,0.079500,0.097367,0.093033,0.067900,0.081133
std,0.106697,0.111283,0.155038,0.134119,0.103199,0.109311,0.145213,0.130474,0.104595,0.112550,0.143712,0.134989,0.100591,0.121281,0.160914,0.152976
min,-0.018700,-0.023600,-0.103500,-0.066300,-0.010700,-0.014800,-0.074500,-0.056400,-0.012700,-0.021500,-0.073300,-0.065100,-0.013500,-0.042000,-0.107700,-0.091400